export const projectData = [{
    id:0,
    name: 'kikilamb',
    description: 'An archived dystopian fashion website utilizing an AR enabled 3D model.',
    link: 'https://www.cameronsworld.net/',
    category: 'web',  
    casestudy: true,
    image1: "kiki_1.webp",
    image2: "afd2.webp",
},{
    id:1,
    name: 'Goober',
    description: 'An e-commerce website hosting a digital version of a physical pubication.',
    link: 'https://gooberovereverything.com/',
    casestudy: false,
    category: 'web',
    image1: "gallery_irl.png",

},{
    id: 2,
    name: 'As It Is',
    description: 'Breath inspired scroll-tied animations on a privacy ensuring site',
    link: 'https://as-it-is-yoga.webflow.io/',
    casestudy: true,
    category: 'web',
    image1: "aii.webp",
}, {
    id: 3,
    name: 'Decadent Identities',
    description: 'A CMS enabled blog inverting devadance and uplifting artists with a layered mirror motif',
    link: 'https://decadent-identities.webflow.io/',
    casestudy: true,
    category: 'web',
    image1: "did_d1.webp",
},{
    id: 4,
    name: 'Debby Friday',
    description: 'An archived hub-style homepage for an artist looking for something that warranted pause.',
    link: 'https://as-it-is-yoga.webflow.io/',
    casestudy: false,
    category: 'web',
    image1: "aii.webp",
},{
    id: 5,
    name: 'hood midcentury modern',
    description: 'graphics, pitches, and research for architectural cannon expansion media.',
    link: 'https://as-it-is-yoga.webflow.io/',
    casestudy: false,
    category: 'design',
    image1: "aii.webp",
},{
    id: 6,
    name: 'After Hours',
    description: 'an app connecting restaurant surplus to those in need',
    link: 'https://as-it-is-yoga.webflow.io/',
    casestudy: false,
    category: 'App',
    image1: "af_d1.webp",
},{
    id: 7,
    name: 'Gallery',
    description: 'a privacy respecting featured with breath based animations',
    link: 'https://as-it-is-yoga.webflow.io/',
    casestudy: true,
    category: 'App',
    image1: "/gallery_d3.webp",
    research1: 'These studies were conducted before and after prototypes in the format of guided and remote surveys.',
    research2: 'In regard to our first prototype: 3 out of 5 people stated they wished there was more information available on the artist featured. 4 out of 5 missed a gallery introduction, something like an about page. Only immediately relevant information is available on the app as is.',
}, ];

